PennyWyse/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PennyWyse.Data;
using PennyWyse.Models;
using PennyWyse.Models.ViewModels;
using Remotion.Linq.Clauses;

namespace PennyWyse.Controllers
{
    public class EventsController : Controller
    {
        //setting private reference to the I.D.F usermanager
        private readonly UserManager<User> _userManager;

        private readonly ApplicationDbContext _context;

        //Getting the current user in the system (whoever is logged in)
        public Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public EventsController(ApplicationDbContext context,
            UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;

        }


        // GET: Events
        [Authorize]
        public async Task<IActionResult> Index(HomeIndexViewModel UserChoice, int? searchId)
        {   

            if (searchId == null)
            {
                searchId = 0;
                var PriceObject = _context.Events
                    .Where(e => e.Price <= searchId);


                return View(PriceObject);
            }
            else
            {
                var PriceObject = _context.Events
                    .Where(e => e.Price <= searchId);


                return View(PriceObject);
            }
        }

      


        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,StartDate,LegalAge,FamilyEvent,Description,InfoURL,ImageURL,City,State,EventType,CreatorId")] Event CreateEvent, int? searchId)
        {

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            User CurUser = await GetCurrentUserAsync();
            CreateEvent.User = CurUser;
            CreateEvent.UserId = CurUser.Id;
            CreateEvent.CreatorId = CurUser.Id;


            if (ModelState.IsValid)
            {
                
                _context.Add(CreateEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new {searchId});
            }
            return View(CreateEvent);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,StartDate,LegalAge,FamilyEvent,Description,InfoURL,ImageURL,City,State,EventType,CreatorId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int searchId)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new {searchId});
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }

    }
}

PennyWyse/Controllers/UserEventsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using PennyWyse.Data;
using PennyWyse.Models;

namespace PennyWyse.Controllers
{
    public class UserEventsController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly ApplicationDbContext _context;

        public UserEventsController(ApplicationDbContext context,
            UserManager<User> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: UserEvents
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();

            var EventList = _context.UserEvents.Include(e => e.Event)
                .Include(e => e.User)
                .Where(ue => ue.UserId == user.Id)
                .ToList();

            if (EventList == null)
            {
                return NotFound();
            }

            return View(EventList);
        }

        // GET: UserEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents
                .Include(u => u.Event)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.UserEventId == id);
            if (userEvent == null)
            {
                return NotFound();
            }

            return View(userEvent);
        }

        // GET: UserEvents/Create
        //public IActionResult Create()
        //{
        //    ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name");
        //    //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
        //    return View();
        //}

        // POST: UserEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( UserEvent userEvent, int? searchId)
        {

            ModelState.Remove("User");
            ModelState.Remove("UserId");

            User CurUser = await GetCurrentUserAsync();
            userEvent.User = CurUser;
            userEvent.UserId = CurUser.Id;


            if (ModelState.IsValid)
            {
                _context.Add(userEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new {searchId});
            }

            //ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name", userEvent.EventId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // GET: UserEvents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents.FindAsync(id);
            if (userEvent == null)
            {
                return NotFound();
            }
            //ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name", userEvent.EventId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // POST: UserEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserEventId,UserId,EventId")] UserEvent userEvent)
        {
            if (id != userEvent.UserEventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserEventExists(userEvent.UserEventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name", userEvent.EventId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // GET: UserEvents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents
                .Include(u => u.Event)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.UserEventId == id);
            if (userEvent == null)
            {
                return NotFound();
            }

            return View(userEvent);
        }

        // POST: UserEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int searchId)
        {
            var userEvent = await _context.UserEvents.FindAsync(id);
            _context.UserEvents.Remove(userEvent);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new {searchId});
    }

        private bool UserEventExists(int id)
        {
            return _context.UserEvents.Any(e => e.UserEventId == id);
        }


        //This little piece o'magic will display current user's list/index.

        public async Task<IActionResult> UserEventsList()
        {

            var user = await GetCurrentUserAsync();

            var EventList = _context.UserEvents.Include(e => e.Event)
                .Include(e => e.User)
                .Where(ue => ue.UserId == user.Id)
                .ToList();

            if (EventList == null)
            {
                return NotFound();
            }

            return View(EventList);
        }





    }
}

PennyWyse/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PennyWyse.Models


@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    string searchId = Context.Request.Query["searchId"].ToString();
}


<!DOCTYPE html>


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PennyWyse</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

    <body>
    <header>
        
        @* JD--- Validating user before sharing *@
        @if (SignInManager.IsSignedIn(User))
        {
            <nav class="navbar navbar-fixed-top navbar-expand-sm navbar-toggleable-sm navbar-black text-white bg-black border-bottom box-shadow mb-3">
                <div class="container">
                   
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" asp-route-searchId="@searchId"><img class="logoImage" height="75" width="150" src="/PWLogoLight.png" alt="I am a logo"/></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                          
                            
                            @if (@searchId != "")
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Events" asp-action="Index" asp-route-searchId="@searchId">Current Search</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="UserEvents" asp-action="Index" asp-route-searchId="@searchId"> Your Event List </a>
                            </li>

                        </ul>

                        
                    </div>
                    
                </div>

            </nav>
        }
            
        
    
    </header>

    <div class="container">
          
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>



    @* JD--- Validating user before sharing *@
 
    
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - PennyWyse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
   


        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
</html>